#!/bin/bash

downloadFile()
{
   local url="$1"
   local target="$2"

   if [ ! -f "$target" ]
   then
      wget "$url" -O "$target"
   fi
}

CURDIR=$(dirname $0)

downloadFile "https://releases.hashicorp.com/consul/1.5.1/consul_1.5.1_linux_amd64.zip" "${CURDIR}/consul.zip"
downloadFile "https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_amd64.zip" "${CURDIR}/consul-template.zip"
