#!/bin/sh

set -e

SCRIPT_NAME=$(basename $0)
SCRIPT_DIR=$(dirname $0)

CUR_DIR=$(pwd)

# Print an help message explaining the use of this program.
usage()
{
   cat >&2 <<-EOF

   Usage: $SCRIPT_NAME [-r|-h]

   This program automatically detects your project type and invokes
   the proper builder accordingly.
   As of now supported project types are :
   - RPM projects (i.e. projects with RPM builds)
   - Java Maven projects, with the system attempting to create RPM packages for WAR and Spring Boot apps.

   This script takes the following optional parameters into account :
   * -h : print this help message
   * -r : create a release.

EOF
}

# Print a log message.
# PARAMS :
# - the message to print.
infoLog()
{
   echo >&2 "$1"
}

# Return the RPM repo prefix if it exists,
# otherwise an empty string.
# RETURNS :
# - the RPM repo prefix
getRpmRepoPrefix()
{
   local settingsFile="/etc/gojulrpmbuildtools/maven_repo.properties"

   [ -f "$settingsFile" ] || echo ""

   local mavenRepoPrefix=$(grep "^MAVEN_RPM_REPO_PREFIX=" /etc/gojulrpmbuildtools/maven_repo.properties) 

   [[ -z "$mavenRepoPrefix" ]] && echo "" || echo ${mavenRepoPrefix#MAVEN_RPM_REPO_PREFIX=}
}

# Check if the project is an RPM project,
# false otherwise.
# RETURNS :
# - a non-empty string if the project is an RPM
# project, false otherwise. 
isRpmProject()
{
   cd "$CUR_DIR"
   [ -f "project-info.properties" ] || echo ""

   local specFileCount=$(find . -mindepth 2 -maxdepth 2 -type f -name "*.spec" | wc -l)

   [[ $specFileCount -gt 0 ]] && echo "rpm" || echo ""
}

# Build RPM project for development purposes.
buildRpmForDevelopment()
{
   infoLog "Building RPM project for development purposes"
   cd "$CUR_DIR"

   build_packages.sh
}

# Build RPM project for release
buildRpmForRelease()
{
   infoLog "Building RPM project for release purposes"

   cd "$CUR_DIR"

   local rpmRepoPrefix=$(getRpmRepoPrefix)
   [[ -z "$rpmRepoPrefix" ]] && infoLog "Packages won't be put under a sub-repo of the repo you've set up" || infoLog "Packages will be put under the subrepo $rpmRepoPrefix of the repo you've set up"

   create_rpm_release.sh "$rpmRepoPrefix"
}

# Return true if the project is a Maven project,
# false otherwise.
# RETURNS :
# - a non-empty string if the project is a Maven project, an empty one otherwise.
isMavenProject()
{
   cd "$CUR_DIR"
   [ -f pom.xml ] && echo "Maven" || echo ""
}

# Return true if the specified project is a Maven WAR
# project, false otherwise.
# RETURN :
# - a non-empty string if the specified project is a Maven WAR
# project, an empty string otherwise.
isMavenWarProject()
{
   cd "$CUR_DIR"
   grep "<packaging>war</packaging>" $(find . -name "pom.xml") > /dev/null && echo "Maven WAR" || echo ""
}

# Return true if the specified project is a Maven SpringBoot
# project, false otherwise.
# RETURN :
# - a non-empty string if the specified project is a Maven Spring
# Boot project, an empty string otherwise.
isMavenSpringBootProject()
{
   cd "$CUR_DIR"
   grep "<artifactId>spring-boot-maven-plugin</artifactId>" $(find . -name "pom.xml") > /dev/null && echo "Spring Boot" || echo ""

}

# Build a Maven project for development purposes.
buildMavenForDevelopment()
{
   infoLog "Building Maven project for development purposes"

   cd "$CUR_DIR"
   mvn clean deploy
}

# Publishes the RPM packages found in the current directory,
# which were generated by an automated RPM generation script.
publishGeneratedRpms()
{
   local rpmRepoPrefix=$(getRpmRepoPrefix)

   for i in $(find . -type f -name "*.rpm"|grep "rpmResults")
   do
       publish_rpm.sh "$i" "$rpmRepoPrefix"
   done
}

# Build a Maven project for release purposes.
buildMavenForRelease()
{
   infoLog "Building Maven project for release purposes"

   cd "$CUR_DIR"
   mvn -B clean release:prepare release:perform

   cd target/checkout

   if [[ -n "$(isMavenSpringBootProject)" ]]
   then
      infoLog "Found SpringBoot project - building Spring Boot RPMs"
      build_springboot_rpm.sh
   elif [[ -n "$(isMavenWarProject)" ]]
   then
      infoLog "Found WAR project - building WAR RPMs"
      build_war_rpm.sh
   else
      infoLog "No specific WAR or Spring Boot app found"
   fi

   publishGeneratedRpms
}

# Build the project
# PARAM :
# - the project type.
buildProject()
{
   local projectType="$1"

   if [[ -z "$RELEASE_MODE" ]]
   then
      build${projectType}ForDevelopment
   else
      build${projectType}ForRelease
   fi
}

if [ "$1" == "-h" ]
then
   usage
   exit 0
elif [ "$1" == "-r" ]
then
   RELEASE_MODE=1
elif [ $# -ne 0 ]
then
   infoLog "Bad argument count or invalid argument !"
   usage
   exit 1
fi

if [[ -n "$(isMavenProject)" ]]
then
   buildProject "Maven"
elif [[ -n "$(isRpmProject)" ]]
then
   buildProject "Rpm"
else
   infoLog "Unknown project type - Aborting"
fi
