#!/bin/bash
#
# gojultomcat         Gojul's Tomcat Start/Stop/Restart scripts
# processname: tomcat
# chkconfig: - 80 20
### BEGIN INIT INFO
# Provides: gojultomcat
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Description: Release implementation for Servlet 2.5 and JSP 2.1
# Short-Description: start and stop tomcat
### END INIT INFO

SCRIPT_NAME=$(basename $0)

export CATALINA_HOME=/usr/share/gojultomcat
export CATALINA_BASE=/home/gojultomcat
export CATALINA_PID=/var/run/gojultomcat/gojultomcat.pid
export JAVA_HOME=/usr/lib/jvm/java-openjdk
export TOMCAT_USER=gojultomcat

# For SELinux we need to use 'runuser' not 'su'
if [ -x "/sbin/runuser" ]; then
    SU="/sbin/runuser -s /bin/sh"
else
    SU="/bin/su -s /bin/sh"
fi

. /etc/rc.d/init.d/functions

start() 
{
   rm -rf $CATALINA_BASE/temp/* $CATALINA_BASE/work/*
   $SU $TOMCAT_USER $CATALINA_HOME/bin/catalina.sh start
}

stop()
{
   $SU $TOMCAT_USER $CATALINA_HOME/bin/catalina.sh stop
}

restart()
{
   $SU $TOMCAT_USER $CATALINA_HOME/bin/catalina.sh restart
}

rh_status()
{
   status -p "$CATALINA_PID" gojultomcat
}

usage()
{
   echo >&2 "$SCRIPT_NAME (start|stop|restart|status)"
}

case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      restart
      ;;
   status)
      rh_status
      ;;
   *)
      usage
      exit 1
      ;;
esac
