#!/bin/bash
#
# gojultomcat         Gojul's Tomcat Start/Stop/Restart scripts
# processname: tomcat
# chkconfig: - 80 20
### BEGIN INIT INFO
# Provides: gojultomcat
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Description: Release implementation for Servlet 2.5 and JSP 2.1
# Short-Description: start and stop tomcat
### END INIT INFO

set -e

SCRIPT_NAME=$(basename $0)

export CATALINA_HOME=/usr/share/gojultomcat
export CATALINA_BASE=/home/gojultomcat
export CATALINA_PID=/var/run/gojultomcat/gojultomcat.pid
export JAVA_HOME=/usr/lib/jvm/java-openjdk
export TOMCAT_USER=gojultomcat

# For SELinux we need to use 'runuser' not 'su'
if [ -x "/sbin/runuser" ]; then
    SU="/sbin/runuser -s /bin/sh"
else
    SU="/bin/su -s /bin/sh"
fi


start() 
{
   $SU $TOMCAT_USER $CATALINA_HOME/bin/catalina.sh start
}

stop()
{
   $SU $TOMCAT_USER $CATALINA_HOME/bin/catalina.sh stop
}

restart()
{
   $SU $TOMCAT_USER $CATALINA_HOME/bin/catalina.sh restart
}

usage()
{
   echo >&2 "$SCRIPT_NAME (start|stop|restart)"
}

case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      restart
      ;;
   *)
      usage
      exit 1
      ;;
esac
