#!/bin/bash

CURDIR=$(dirname $0)
TARGETFILE="${CURDIR}/confluent-distrib.tgz"

if [ ! -f "$TARGETFILE" ]
then
   wget http://packages.confluent.io/archive/5.0/confluent-oss-5.0.0-2.11.tar.gz -O "$TARGETFILE"
fi
